#!/usr/bin/env bash
# git is needed at the first place anyways
gh="gh"
glab="glab"

# Check the OS type to determine the correct install command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $gh
  brew install $glab
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) &&
      sudo mkdir -p -m 755 /etc/apt/keyrings &&
      out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg &&
      cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null &&
      sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg &&
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null &&
      sudo apt update &&
      sudo apt install gh -y
  # Check if it's Arch Linux
  elif grep -q "Arch Linux" /etc/os-release; then
    sudo pacman -Syu --noconfirm $gh
    sudo pacman -Syu --noconfirm $glab
  else
    echo "Unsupported Linux distribution for $gh and $glab."
  fi
else
  echo "Unsupported OS for $gh and $glab."
fi
