#!/usr/bin/env bash
program="neovim"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
  # Clipboard support for Neovim on macOS
  brew install pbcopy
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  # TODO: maybe change this to using a package manager?
  if grep -q "Ubuntu" /etc/os-release; then
    version="v0.10.2"
    if [ ! -z $NVIM_VERSION ]; then
      version="$NVIM_VERSION"
    fi

    echo "version: \"$version\""

    # neovim btw
    if [ ! -d $HOME/neovim ]; then
      git clone https://github.com/neovim/neovim.git $HOME/neovim
    fi

    sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev

    git -C ~/neovim fetch --all
    git -C ~/neovim checkout $version

    make -C ~/neovim clean
    make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make -C ~/neovim install

    # Clipboard support for Neovim on Ubuntu
    sudo apt -y install xclip xsel wl-clipboard

    git clone https://github.com/ThePrimeagen/harpoon.git $HOME/personal/harpoon
    cd $HOME/personal/harpoon
    git fetch
    git checkout harpoon2

    git clone https://github.com/ThePrimeagen/vim-apm.git $HOME/personal/vim-apm
    git clone https://github.com/ThePrimeagen/vim-with-me.git $HOME/personal/vim-with-me
    git clone https://github.com/ThePrimeagen/vim-arcade.git $HOME/personal/vim-arcade
    git clone https://github.com/ThePrimeagen/caleb.git $HOME/personal/caleb
    git clone https://github.com/nvim-lua/plenary.nvim.git $HOME/personal/plenary

    wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
    tar zxpf luarocks-3.11.1.tar.gz
    cd luarocks-3.11.1
    ./configure && make && sudo make install
    sudo luarocks install luacheck
  elif grep -q "Arch" /etc/os-release; then
    echo "Installing $program on Arch Linux..."
    sudo pacman -Syu --noconfirm $program

    # Clipboard support for Neovim on Arch with Hyprland (Wayland)
    sudo pacman -S --noconfirm wl-clipboard xclip xsel
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
