#!/usr/bin/env bash
program="zed"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install --cask $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    curl -f https://zed.dev/install.sh | sh
  elif grep -q "Arch" /etc/os-release; then
    echo "Unsupported OS for $program."
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
