#!/usr/bin/env bash
program="cmake"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    sudo apt update
    sudo apt install $program -y
  # Check if it's Arch Linux or any Arch-based distro (e.g., Manjaro)
  elif grep -q "Arch" /etc/os-release || grep -q "Manjaro" /etc/os-release; then
    sudo pacman -Syu --noconfirm $program
  else
    echo "Unsupported Linux distro for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
