#!/usr/bin/env bash
program="sesh"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    go install github.com/joshmedeski/sesh/v2@latest
  elif grep -q "Arch" /etc/os-release || grep -q "Manjaro" /etc/os-release; then
    yay -S sesh-bin
  else
    echo "Unsupported Linux distro for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
