#!/usr/bin/env bash
program="docker"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    ## Apt
    ## https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

    sudo apt-get -y update
    sudo apt-get -y install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    sudo groupadd $program
    sudo usermod -aG $program $USER

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
      sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
    sudo apt-get -y update

    ## Install
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # Check if it's Arch Linux or any Arch-based distro (e.g., Manjaro)
  elif grep -q "Arch" /etc/os-release || grep -q "Manjaro" /etc/os-release; then
    # Install Docker on Arch Linux using pacman
    sudo pacman -Syu --noconfirm docker
    # Enable and start Docker service
    sudo systemctl enable --now docker
    sudo groupadd docker
    sudo usermod -aG docker $USER
    echo "Docker installed and started. Please log out and log back in to use Docker without sudo."
  else
    echo "Unsupported Linux distro for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
