#!/usr/bin/env bash
program="docker-compose"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    echo "Unsupported OS for $program."
  # Check if it's Arch Linux or any Arch-based distro (e.g., Manjaro)
  elif grep -q "Arch" /etc/os-release || grep -q "Manjaro" /etc/os-release; then
    # Install Docker Compose from the Arch repository (if available)
    sudo pacman -Syu --noconfirm docker-compose
    # Alternatively, if you want to install the latest version using the official Docker Compose release:
    # sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    # sudo chmod +x /usr/local/bin/docker-compose
  else
    echo "Unsupported Linux distro for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
