#!/usr/bin/env bash
program="kubernetes"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
  brew install kubernetes-cli
  brew install k9s
  brew install --cask lens
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    echo "Unsupported OS for $program."
  elif grep -q "Arch" /etc/os-release; then
    echo "Installing $program on Arch Linux..."
    echo "Unsupported OS for $program."
    #TODO: Add later
    #yay -Syu --noconfirm $program
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
