#!/usr/bin/env bash
program="gcc"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    sudo apt install $program
  # Check if it's Arch Linux
  elif grep -q "Arch Linux" /etc/os-release; then
    sudo pacman -S --noconfirm $program
  else
    echo "Unsupported Linux distribution for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
