#!/usr/bin/env bash
program="ghostty"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install --cask $program
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    sudo apt update
    sudo apt install llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git

    wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
    tar -xvf /tmp/zig.tar.xz -C $HOME/.local
    export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

    git clone git@github.com:ghostty-org/ghostty.git $HOME/personal/ghostty

    (
      cd $HOME/personal/ghostty
      zig build -p $HOME/.local -Doptimize=ReleaseFast
    )
  # Check if it's Arch Linux
  elif grep -q "Arch Linux" /etc/os-release; then
    sudo pacman -Syu --noconfirm $program

    #sudo pacman -S --noconfirm llvm lld clang git

    ## Install Zig from official Arch repo if available
    #if ! pacman -Qs zig > /dev/null; then
    #  wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
    #  tar -xvf /tmp/zig.tar.xz -C $HOME/.local
    #fi
    #export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

    #git clone git@github.com:ghostty-org/ghostty.git $HOME/personal/ghostty

    #(
    #  cd $HOME/personal/ghostty
    #  zig build -p $HOME/.local -Doptimize=ReleaseFast
    #)
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
