#!/usr/bin/env bash
program="yazi"

# Check the OS type to determine the correct find command
if [[ "$OSTYPE" == "darwin"* ]]; then
  #NOTE: You can install Yazi (and the optional dependencies):
  # brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide imagemagick font-symbols-only-nerd-font
  brew install $program ffmpeg-full sevenzip jq poppler fd ripgrep fzf zoxide resvg imagemagick-full font-symbols-only-nerd-font
  brew link ffmpeg-full imagemagick-full -f --overwrite
  ya pkg add yazi-rs/flavors:catppuccin-mocha
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux: Check if it's Ubuntu
  if grep -q "Ubuntu" /etc/os-release; then
    #NOTE: dependencies
    #apt install ffmpeg 7zip jq poppler-utils fd-find ripgrep fzf zoxide imagemagick
    # In Debian/Ubuntu, you currently need to manually build Yazi or download our official binary release.
    echo "Unsupported OS for $program."
  elif grep -q "Arch" /etc/os-release; then
    echo "Installing $program on Arch Linux..."
    sudo pacman -Syu --noconfirm $program
  else
    echo "Unsupported OS for $program."
  fi
else
  echo "Unsupported OS for $program."
fi
